version: '2'

volumes:
  dist: {}

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    volumes:
      - ./src:/app/src
      - dist:/app/dist
    restart: unless-stopped
    command: npm run build && npm run start

  # labelstatic:
  #   image: httpd:latest
  #   volumes:
  #     - dist:/usr/local/apache2/htdocs/
  #   depends_on:
  #     - web
  #   ports:
  #     - "9000:80"